default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: chatty_development

test:
  <<: *default
  database: peatio_test

